# coding: utf-8

"""
    PowerDNS Authoritative HTTP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.config_api import ConfigApi


class TestConfigApi(unittest.TestCase):
    """ ConfigApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.config_api.ConfigApi()

    def tearDown(self):
        pass

    def test_get_config(self):
        """
        Test case for get_config

        Returns all ConfigSettings for a single server
        """
        pass

    def test_get_config_setting(self):
        """
        Test case for get_config_setting

        Returns a specific ConfigSetting for a single server
        """
        pass


if __name__ == '__main__':
    unittest.main()
