# coding: utf-8

"""
    PowerDNS Authoritative HTTP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.models.record import Record


class TestRecord(unittest.TestCase):
    """ Record unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRecord(self):
        """
        Test Record
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = swagger_client.models.record.Record()
        pass


if __name__ == '__main__':
    unittest.main()
