# coding: utf-8

"""
    PowerDNS Authoritative HTTP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.servers_api import ServersApi


class TestServersApi(unittest.TestCase):
    """ ServersApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.servers_api.ServersApi()

    def tearDown(self):
        pass

    def test_list_server(self):
        """
        Test case for list_server

        List a server
        """
        pass

    def test_list_servers(self):
        """
        Test case for list_servers

        List all servers
        """
        pass


if __name__ == '__main__':
    unittest.main()
