# coding: utf-8

"""
    PowerDNS Authoritative HTTP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.0.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.zonemetadata_api import ZonemetadataApi


class TestZonemetadataApi(unittest.TestCase):
    """ ZonemetadataApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.zonemetadata_api.ZonemetadataApi()

    def tearDown(self):
        pass

    def test_create_zone_metadata(self):
        """
        Test case for create_zone_metadata

        Creates a set of metadata entries
        """
        pass

    def test_delete_zone_metadata_kind(self):
        """
        Test case for delete_zone_metadata_kind

        Delete all items of a single kind of domain metadata.
        """
        pass

    def test_list_zone_metadata(self):
        """
        Test case for list_zone_metadata

        Get all the MetaData associated with the zone.
        """
        pass

    def test_list_zone_metadata_kind(self):
        """
        Test case for list_zone_metadata_kind

        Get the content of a single kind of domain metadata as a list of MetaData objects.
        """
        pass

    def test_modify_zone_metadata_kind(self):
        """
        Test case for modify_zone_metadata_kind

        Modify the content of a single kind of domain metadata.
        """
        pass


if __name__ == '__main__':
    unittest.main()
