# coding: utf-8

"""
    PowerDNS Authoritative HTTP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.0.11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import pdns_api_client
from pdns_api_client.rest import ApiException
from pdns_api_client.apis.search_api import SearchApi


class TestSearchApi(unittest.TestCase):
    """ SearchApi unit test stubs """

    def setUp(self):
        self.api = pdns_api_client.apis.search_api.SearchApi()

    def tearDown(self):
        pass

    def test_search_data(self):
        """
        Test case for search_data

        Search the data inside PowerDNS
        """
        pass

    def test_search_log(self):
        """
        Test case for search_log

        Query the log, filtered by search_term.
        """
        pass


if __name__ == '__main__':
    unittest.main()
