# coding: utf-8

"""
    PowerDNS Authoritative HTTP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.0.10
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import pdns_api_client
from pdns_api_client.rest import ApiException
from pdns_api_client.apis.stats_api import StatsApi


class TestStatsApi(unittest.TestCase):
    """ StatsApi unit test stubs """

    def setUp(self):
        self.api = pdns_api_client.apis.stats_api.StatsApi()

    def tearDown(self):
        pass

    def test_get_stats(self):
        """
        Test case for get_stats

        Query statistics.
        """
        pass


if __name__ == '__main__':
    unittest.main()
