# coding: utf-8

"""
    PowerDNS Authoritative HTTP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.0.11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import pdns_api_client
from pdns_api_client.rest import ApiException
from pdns_api_client.apis.zonemetadata_api import ZonemetadataApi


class TestZonemetadataApi(unittest.TestCase):
    """ ZonemetadataApi unit test stubs """

    def setUp(self):
        self.api = pdns_api_client.apis.zonemetadata_api.ZonemetadataApi()

    def tearDown(self):
        pass

    def test_create_metadata(self):
        """
        Test case for create_metadata

        Creates a set of metadata entries
        """
        pass

    def test_delete_metadata(self):
        """
        Test case for delete_metadata

        Delete all items of a single kind of domain metadata.
        """
        pass

    def test_get_metadata(self):
        """
        Test case for get_metadata

        Get the content of a single kind of domain metadata as a list of MetaData objects.
        """
        pass

    def test_list_metadata(self):
        """
        Test case for list_metadata

        Get all the MetaData associated with the zone.
        """
        pass

    def test_modify_metadata(self):
        """
        Test case for modify_metadata

        Modify the content of a single kind of domain metadata.
        """
        pass


if __name__ == '__main__':
    unittest.main()
