# coding: utf-8

"""
    PowerDNS Authoritative HTTP API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)

    OpenAPI spec version: 0.0.11
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import pdns_api_client
from pdns_api_client.rest import ApiException
from pdns_api_client.apis.zonecryptokey_api import ZonecryptokeyApi


class TestZonecryptokeyApi(unittest.TestCase):
    """ ZonecryptokeyApi unit test stubs """

    def setUp(self):
        self.api = pdns_api_client.apis.zonecryptokey_api.ZonecryptokeyApi()

    def tearDown(self):
        pass

    def test_create_crypto_key(self):
        """
        Test case for create_crypto_key

        Creates a Cryptokey
        """
        pass

    def test_delete_cryptokey(self):
        """
        Test case for delete_cryptokey

        This method deletes a key specified by cryptokey_id.
        """
        pass

    def test_list_crypto_keys(self):
        """
        Test case for list_crypto_keys

        Get all CryptoKeys for a zone, except the privatekey
        """
        pass

    def test_list_cryptokey(self):
        """
        Test case for list_cryptokey

        Returns all data about the CryptoKey, including the privatekey.
        """
        pass

    def test_modify_cryptokey(self):
        """
        Test case for modify_cryptokey

        This method (de)activates a key from zone_name specified by cryptokey_id
        """
        pass


if __name__ == '__main__':
    unittest.main()
